### PR TITLE
adding dataViewer

### PR DESCRIPTION
**Pull request by padpadpadpad**
There is a gif of getting it going on the GitHub link.

### CODE REVIEW

**Comment by daattali** [comment]
Hi @padpadpadpad , I don't think this package provides an actual RStudio addin , does it? I installed it and did not see a new addin in the addins menu. I also don't see an addin defined in the package itself.

**Comment by padpadpadpad** [comment]
Funny @daattali. It is an addin by my definition (i.e. it launches a viewer inside RStudio and using shiny::runGadget(). Could it be because it takes more than a single argument?

**Comment by daattali** [comment]
An RStudio addin by definition (by definition by RStudio) has to be registered in RStudio using a file in `inst/rstudio/addins.dcf` (as described in the [official addin docs](https://rstudio.github.io/rstudioaddins/#registering-addins)) and that will in turn make sure it appears under the Addins menu in rstudio. Not my subjective definition, that's technically what it is

**Comment by daattali** [comment]
If you make it a proper addin it'll make it easier for people to discover (since it'll show up in the addins menu) so it doesn't hurt anyway

**Comment by daattali** [comment]
Closing due to lack of activity. Feel free to re-submit

**Pull request closed without merging**
