### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dracodoc**
add addin `namebrowser`

### CODE REVIEW

**Comment by daattali** [comment]
Very nice idea, definitely a useful addin! But I can't accept it in its current form because it doesn't work for me.

```
> namebrowser::searchname()

Listening on http://127.0.0.1:5760
Warning: Error in if: argument is of length zero
Stack trace (innermost first):
    3: shiny::runApp
    2: shiny::runGadget
    1: namebrowser::searchname
Error : argument is of length zero
```

I tried selecting a word in the console, in the source editors, I tried passing in an argument to that function, I tried all sorts of things and couldn't get the addin to work.  

Also, it seems excessive to have three addins for this - can't they all be combined into one? I feel like the "scan" addin can just be a simple button inside the addin, and the other two can be merged into one and just have two tabs.  

I can see from the gif and the images that you put a lot of effort into this and it's definitely a good idea, but I don't feel comfortable advertising it with these problems.  Once you fix those issues feel free to submit a PR again! Thanks!

**Comment by dracodoc** [comment]
Hi @daattali , thanks for the test, can you expand the Stack trace and post the detailed error message? 

There is only one package, one addin, but 3 menu items. I have more functions in package, but chose to register these 3 functions because this way user can assign keyboard shortcut to the 2 most used functions `search name` and `search regex`. I also felt the `update name` is needed to remind user to sync the name table with his installed packages.

If you felt there is no need for all 3 menu item, you can edit a file and remove the registration so they doesn't appear in the menu. It doesn't affect the package usage.

I'll add a section in package readme about this. Actually I think I wrote about this in my other addin, because that one have more menu items, and most user may only need some of them.

**Comment by daattali** [comment]
That was the whole stack trace. I might be able to get a more detailed
trace if I download the source code and debug it, but I unfortunately don't
have time for that. I see what you're saying about the 3 menu items. I can
just give my advice based on talking to a lot of users of other packages
and seeing a lot of feedback - people don't like it when they install one
thing and the menu gets "spammed" with multiple items , resulting in one
package taking up so much of the available slots.  And since these are all
very related functions it even makes it more sensible to have them
together. I understand your point re: wanting to be able to add different
shortcuts to different functions, but if you think about it from the
prespective of the average user rather than yourself: you're obviously
highly technical and capable in R, but the vast majority of rstudio users
don't add their own custom shortcuts to addins (most don't even know it's
possible). There are likely a lot more people who will think having 3 menu
items is annoying. Those who know how to add a shortcut might also know how
to edit the config file for the addin, but those who can't add a shortcut
(most people) also will not be able to alter the config so that only one
menu item shows up.

On a similar note, I also think the miscaddins package should be broken
into separate packages because it contains a few very different addins with
very different functionality. It's much better to keep similar things
together and distinct things in separate packages. By installing these two
packages, more than half the slots in the addins menu is gone. I actually
found the microbenchmark addin useful, but I removed your package because
it really bugged me that there were 5 separate entries and I only wanted 1
and it was really cluttering my space.  The addins are very good and useful
nonetheless

---
http://deanattali.com

**Comment by dracodoc** [comment]
OK, I forgot you don't have source code by just installing package. Will run `options(shiny.trace=TRUE)` before running the addin give you more information?

I totally understand the frustration you had about the addin menu -- I found it became a mess after installing just several addins. That's why I added a naming prefix in all the menu items I registered, to make them a little bit more organized.

As for `namebrowser` addin, I wanted to make the regex search as an option in regular search dialog. But I didn't find way to change that after the dialog initialized, so I have to use two separate functions, thus two menu items. 

Actually I think it may be possible to make an addin to allow user to select which menu item to be displayed. But I don't want add yet another addin menu item, so I'll submit a feature request to RStudio and see what they say. If they didn't do it, I'll try to make one.

**Comment by daattali** [comment]
I do appreciate adding the prefix to the name, it does help, but it's still
less friendly in my opinion than just combining similar features into one
:) I've spoken to many useRs about this issue and the consensus was that
fewer addins is better and that it's not good to be intrusive by adding
more items to the addins menu without the user really wanting it. I've also
spoken to a couple RStudio folks about the issue of choosing what addins to
show in the menu and they do realize it's not perfect but for now it's just
a list of 15 most recently used. It didn't sound like they had it too high
on their priorities to let users rearrange those menu items
(understandably, they do have a million other things to work on :) I just
tried installing on a different laptop and now I get an error about
"dataTableProxy" not existing in DT. I'm guessing this is an issue of me
having an old version of DT. You should probably specify a minimum required
version of packages that are using fairly new features. Regarding combining
regex and regular search into one: I'm certain it can be done, form the
GIFs it looks like they're almost identical. It really really doesn't make
sense to make two separate menu items for a function with different
parameters. I'm sorry if I'm coming off very opinianated but I think these
addins are really great and useful so I want to make sure they're also very
user friendly so that people will be more inclined to use them.

---
http://deanattali.com

**Comment by dracodoc** [comment]
Yes the addin do need the newest version 'DT', but it's only available through github.The 'imports' field in 'description' only install required packages from CRAN. That's why I specifically wrote about install 'DT' from github in the installation instructions, but installing the addin from 'addinlist' probably didn't do that. 

I'll have a look at if the package can check package version and give meaningful error messages. 

As for the regex seach, it really **should** be a switch in dialog instead of a separate menu item and that's what I wanted in the beginning. However I only found limited things that can be done after the DT table is initialized, which doesn't include changing regex search mode. I will ask @yihui about this and see if it can be done.

**Comment by daattali** [comment]
if your package requires a certain version of DT, then that version should
be specified in the DESCRIPTION. You can use the "Remotes:" field to
specify that it's from github. To change regex on/off you can probably
re-render the DT table to specify different config options in the worst
case scenario. It might not be ideal solution for you, but it's much better
for the users.

---
http://deanattali.com

**Comment by dracodoc** [comment]
I didn't know the `Remotes:` field exist, thanks for pointing it out!

I have updated the DESCRIPTION file. In my test it will install the newest version DT from github automatically now.

@yihui just replied my question about modifying regex mode after table initialization. Since the DataTables API doesn't support it, DT cannot do that either.

I'll check if I can initialize the table again in same dialog.

**Comment by dracodoc** [comment]
OK, now a checkbox in dialog will switch regex mode. Thanks for the push! I wanted to do this in the beginning but didn't have time to further explore it.

I'll need to record all the demo again though :)

**Comment by daattali** [comment]
You can certainly initialize the table again in the renderDatatabke function

**Comment by dracodoc** [comment]
Yes, the checkbox will initialize the table again with new regular expression mode now. Thanks for the suggestions!

**Comment by daattali** [comment]
Just want to ensure the addin can be as best as possible for users :)

---
http://deanattali.com

**Comment by dracodoc** [comment]
OK, I updated screenshots and gif demos. 
@daattali , can you try the addin to see if it work when you have time?

**Comment by daattali** [comment]
Much better! I still strongly believe that it's much nicer to have the "update" function be a button inside the dialog rather than its own menu item - it's essentially taking up space in that menu bar without users asking for it to be there for something that is meant to be clicked on just once and is 100% tied together to an addin. I understand having it a separate menu item makes it more clickable and makes your addin more visible , but I really don't think it's best user experiecnce

**Comment by dracodoc** [comment]
I took some time tried to place the `update` function as a button inside the dialog, then I felt it's too easy to be clicked accidentally. Since this operation can have some risk of corrupt the table if there was some error because not in a clean R session, I think it's better to be separated from the regularly used dialog.

I'll try to make a easier to use function to enable/disable menu items.

**Comment by daattali** [comment]
I think what you're saying if even more of a reason to make it a button
inside the app rather than a menu item. When I first saw it as a menu item
I didn't know what it was for it, it's not at all clear that it's connected
to the addin, so i clicked it and a bunch of errors popped up and I quickly
quit RStudio because I had no idea what's happening. If it's inside the
addin then it makes it more clear that it's related, and you can warn
people after clicking it. You can also make it a much more subtle button
(for example, look at the refresh button I made In the addinslist gadget).

I took some time tried to place the update function as a button inside the
dialog, then I felt it's too easy to be clicked accidentally. Since this
operation can have some risk of corrupt the table if there was some error
because not in a clean R session, I think it's better to be separated from
the regularly used dialog.

I'll try to make a easier to use function to enable/disable menu items.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/daattali/addinslist/pull/46#issuecomment-238401847>,
or mute
the thread

**Comment by dracodoc** [comment]
I agree put the update function in menu could lead to accidental click. 

Since the update function could cause some errors and left packages unloaded in user's environment, it's always recommended to save work and start new R session first. 

I decided to remove it from the addin menu altogether. It is not a frequently use function anyway. I rewrote the addin readme to make it more clear, stressed on always starting a new R session, then user will need to run it from console with `namebrowser::update_name_table()` manually.

**Comment by dracodoc** [comment]
@daattali , can you test if the addin can run without problem in your machine now? 

If there is no more problem, could you please review this PR and merge the commit to your list?

**Comment by daattali** [comment]
Yup looks a lot better!  Now it's in a state that I'd happily accept it 

FYI just a few other small usability issues I would really fix it I were too because they're easy fixes and it just makes the app a lot easier to use

- the load and inert buttons don't do anything if there is no row selected, so why not disable them until a row is selected? (you can use shinyjs::disable(btn, condition = !row_is_selected))
- the table is showing row numbers but these numbers are meaningless and just clutter the table
- when I select/unselect the regex option, the query in the search box gets reset and doesn't remain what it was before

**Comment by daattali** [comment]
Make a new PR please and I'll merge

**Comment by dracodoc** [comment]
@daattali , thanks for the suggestions!

- I experimented with the `shinyjs::diable` method for quite some time. At first RStudio complained for no value for `selector` parameter but I ignored it, since it is not needed when id is provided. Only after several error messages I read the help page again and found I should use `togglestate` instead of `disable` for condition.

  Then I can initialize the table with button disabled, and enable the button when row is selected. But I cannot make it disable again when the row is deselected again. The shiny message said

  ```
RECV {"method":"update","data":{"table_cell_clicked":{"row":19710,"col":2,"value":"observeEvent"},"table_rows_selected":[19710],"table_row_last_clicked":19710}}
SEND {"custom":{"busy":"busy"}}
SEND {"custom":{"shinyjs-toggleState":{"id":"load_package","condition":true}}}
SEND {"custom":{"busy":"idle"}}
RECV {"method":"update","data":{"table_rows_selected":[]}}
```

  I used `table_rows_selected` because `row_is_selected` doesn't seem to work. 

  I'll just stop here for this now, it's better than before anyway.

- I removed the table summary from the table.
- As for keeping input after switching regex mode, I tried to do that at first. However it seemed that put last table's status information into another table's initialization code doesn't work. Because I have to reinitialize the table to switch mode, maybe I need to use some variable to keep that information. Though I cannot find how to get the search input now!

  I felt shiny is powerful and easy to get started, but once I want to anything special or any detailed customization, I need to search through different tutorials, articles, posts to find the small piece information I need. I even solved several problems only by asking DT developer directly.

**Comment by dracodoc** [comment]
After some debugging, I found selecting a row will trigger the event of `input$table_rows_selected`, but deselecting it will not trigger the event, although the shiny trace message said 
`RECV {"method":"update","data":{"table_rows_selected":[]}}`

**Comment by daattali** [comment]
Ah yes sorry it's toggleState(), not disable() if you have a condition.  If
you're listening to the input$rows_selected event using a observeEvent,
then look at the "ignoreNULL" parameter. Yes you're right that shiny is
super easy to get started with and doing any advanced customization is a
ton more work, luckily Yihui and the rest of the guys working on those
things are very helpful :)  If you don't know javascript at all then I
don't think getting the search query is possible

---
http://deanattali.com

**Comment by dracodoc** [comment]
@daattali Thanks for the tip of `ignoreNULL`! Now the buttons will be disable again when row is deselected.

**Pull request closed without merging**
