### PR TITLE
add radiant.data and radiant to the list

### PR DESCRIPTION
**Pull request by vnijs**

### CODE REVIEW

**Comment by daattali** [comment]
are you at useR? haven't seen you

**Comment by daattali** [comment]
GitHub won't let me merge, says there's a conflict, can you send again?

**Comment by vnijs** [comment]
Not at useR unfortunately. Not sure what could cause problems. Lines I added to README.md are pasted below:

| radiant.data | A Shiny interface to visualize, summarize, transform, and combine data | [radiant.data](https://github.com/radiant-rstats/radiant.data) | :x: | [Vincent Nijs](http://rady.ucsd.edu/faculty/directory/nijs) | [Documentation](https://radiant-rstats.github.io/docs) | |
| radiant | A Shiny interface for business analytics in R | [radiant](https://github.com/radiant-rstats/radiant) | :x: | [Vincent Nijs](http://rady.ucsd.edu/faculty/directory/nijs) | [Documentation](https://radiant-rstats.github.io/docs) | |

**Comment by daattali** [comment]
I can add your lines myself, but I like it when the package author literally has the commit so that you'll show up in the history/contributors.  If you don't have the patience to deal with opening a new PR, I'll do it myself, let me know

**Comment by vnijs** [comment]
Will do

**Pull request closed without merging**
