### PR TITLE
add wordcountaddin

### PR DESCRIPTION
**Pull request by benmarwick**

### CODE REVIEW

**Comment by daattali** [comment]
Hmm trying to install this package forced me to install **32** packages

```
Installing 32 packages: DBI, doParallel, foreach, gdata, gender, gridBase, gtools, igraph, irlba, iterators, koRpus, NLP, NMF, openNLP, openNLPdata, pkgmaker, plotrix, qdap, qdapDictionaries, qdapRegex, qdapTools, registry, reports, rJava, rngtools, slam, stringdist, tm, venneuler, wordcloud, xlsx, xlsxjars
```

And it failed for me (Windows)

```
* installing *source* package 'wordcountaddin' ...
** R
** inst
** tests
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
ERROR: lazy loading failed for package 'wordcountaddin'
```

I'm not sure if this error is with your package or with a dependency. Do you know? And do you know if this is a Windows problem only? Am I supposed to change my settings somewhere to tell it where to find my java installation?

**Comment by benmarwick** [comment]
Thanks for the feedback. Java is a huge pain to set up on windows (my main OS), and I agree that 32 packages is a huge dependency list for such a simple package! Looking at [SO](http://stackoverflow.com/questions/17376939/problems-when-trying-to-load-a-package-in-r-due-to-rjava), it seems that your Java error might relate to a mismatch between your Java installation and your system architecture (ie. 32 v 64 bit, as it hints in the error message you reported). 

Another user mentioned struggling with Java to me also, so I've now removed the qdap methods from this add-in (with https://github.com/benmarwick/wordcountaddin/commit/857c55a0211cbfe646e1d30ac616c360228df92c). That removes the need for Java completely, and should more than halve the number of other packages to install.

**Comment by daattali** [comment]
I actually both have java architectures installed because chrome needed the 32 version (yes, strange, I know). Just tried installing again, now only 2 packages had to be installed, and more importantly - it works :)

**Comment by benmarwick** [comment]
Java weirdness is inescapable, it seems. Glad to hear the install was much simpler without qdap and Java, and thanks for adding it to your list. Do let me know if you have any other suggestions for improvement.

**Pull request merged**
