### PR TITLE
add makeImport to addins table

### PR DESCRIPTION
**Pull request by yonicd**

### CODE REVIEW

**Comment by daattali** [comment]
Thanks for submitting. I don't quite understand what this addin does, is this for package development without devtools? I tried looking at the README and still wasn't sure, can you try spelling it out in a foolproof way so that even idiots understand what it's for?

**Comment by yonicd** [comment]
ok. its for dev. when you are building a package to submit to cran and you need to have namespace calls for any function that is being imported.

It is a pain (at least for me) to manually parse through the code looking for all the `*::*` and writing it in the roxygen header.

this function does that for you. 

you can write normally your script with the namespace calls and in the end run the function and you can paste the output into the header. 

the function is written to work on files or whole dirs (like in a package R subdir), and the addin is just a call to one file, that is the one in the `rstudioapi::getActiveDocumentContext()$contents`

**Comment by yonicd** [comment]
an example on one of your [files](https://github.com/daattali/timevis/blob/master/R/timevis.R) 

```r
makeImport('https://raw.githubusercontent.com/daattali/timevis/master/R/timevis.R')

https://raw.githubusercontent.com/daattali/timevis/master/R/timevis.R
#' @importFrom htmltools tags
#' @importFrom htmlwidgets createWidget shinyWidgetOutput shinyRenderWidget
#' @importFrom rmarkdown html_dependency_jquery html_dependency_bootstrap
```

**Comment by daattali** [comment]
Oh I see, that is useful. A very common approach (I think it's the recommended approach?)  is to not use `importFrom`, and just namespace all the functions and list the packages as `Imports` in the DESCRIPTION file. Does this addin help with finding all the packages and listing them in DESCRIPTION?

I may be misunderstanding something, but is it necessary to use `importFrom` if you're also namespacing anyway?

**Comment by yonicd** [comment]
yes there is a namespace option. it is meant to go over a whole dir to summarise the imported packages. 

```r
makeImport(file=path,format='namespace')
```

for the import/importFrom I found that doing only import it creates a lot of conflicts and when you build w oxygen, since you dont have control the order which they are loaded. for example plyr/dplyr you still get the conflict warning if dplyr is loaded before plyr. 

My guess was that handling importFrom was seen as too big an ask from (new) developers to maintain, that is why the recommend of import. 

to control a threshold of how many functions are too many for importFrom and its just the same to import the whole package I put in `cut`.

where if number of functions per imported packages exceeds cut the printout is just `import(pkg)` and not `importFrom(pkg,*)`

```r
makeImport(file=path,format='namespace',cut=5)
```

there isnt really a good way to use that in the addin, so i just set format to `'oxygen'` and cut to `NULL` (only importFrom).

**Comment by yonicd** [comment]
in theory the `makeImport(file=path,format='namespace')` option would be a better builtin option in roxygen that maintains for you the NAMESPACE file and no more  syntax in the roxygen header in each function

**Comment by daattali** [comment]
I see, ok, that makes it more clear :+1:

**Pull request merged**
